apiVersion: v1
kind: Service
metadata:
  name: hello-kube-service
  labels:
    app: hello-kube
    release: "1.0"
    env: develop  
spec:
  selector:
    app: hello-kube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
