apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-sts
spec:
  serviceName: "mongo-service"
  replicas: 3
  selector:
    matchLabels:
      role: mongo  # Label selector that determines which pods are members of the StatefulSet
  template:
    metadata:
      labels:
        role: mongo  # Labels to be applied to all Pods in the StatefulSet
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
